In [348]:

def apply_factor(product1,product2):
    z=1
    y=1

    if product1=='RB' and product2 =='RB':
        z=42
        y=42
    elif product1=='HO' and product2 =='HO':
        z=42
        y=42
    elif product1=='RB' and product2 =='HO':
        z=42
        y=42
    elif product1=='HO' and product2 =='RB':
        z=42
        y=42
    elif product1=='HO' and product2 =='CL':
        z=42
        y=1  
    elif product1=='RB' and product2 =='CL':
        z=42
        y=1          
    elif product1=='CL' and product2 =='B':
        z=1
        y=1       
    elif product1=='G' and product2 =='G':
        z=(1/7.45)
        y=(1/7.45)
    elif product1=='G' and product2 =='B':
        z=(1/7.45)
    elif product1=="HO" and product2=='G':
        z=42
        y=(1/7.45)
    
    else:
        pass

    return z,y




class Mth_1(object):
    
    def __init__(self):
        pass
        
    def pdt_type1(self):
        
        product=''
        while True:
            inst=int(raw_input('Please input the number of the product you want to see the seasonals: 1) Brent 2) Gasoil 3) HO 4) RBOB 5) WTI: '))
    
            if inst==1:
                product='B'
                break
            elif inst==2:
                product='G'
                break   
            elif inst==3:
                product='HO'
                break      
            elif inst==4:
                product='RB'
                break       
            elif inst==5:
                product='CL'
                break       
            else:
                print 'You did not input a correct number. Please try again.'
        
        return product
    
    def mth_no1(self):
        month=''
        while True:
            Mth=int(raw_input('Please input the month of the contract which you wish to evaluate in numbers from 1-12: '))
    
            if Mth==1:
                month='Jan'
                break
            elif Mth==2:
                month='Feb'
                break   
            elif Mth==3:
                month='Mar'
                break   
            elif Mth==4:
                month='Apr'
                break   
            elif Mth==5:
                month='May'
                break          
            elif Mth==6:
                month='Jun'
                break   
            elif Mth==7:
                month='Jul'
                break   
            elif Mth==8:
                month='Aug'
                break   
            elif Mth==9:
                month='Sep'
                break   
            elif Mth==10:
                month='Oct'
                break   
            elif Mth==11:
                month='Nov'
                break   
            elif Mth==12:
                month='Dec'
                break 
            else:
                print 'You did not input a correct number. Please try again.'
        
        return month      

    
class Mth_2(object):
    
    def __init__(self):
        pass
        
    def pdt_type2(self):
        
        product=''
        while True:
            inst=int(raw_input('Please input the number of the product you want to see the seasonals: 1) Brent 2) Gasoil 3) HO 4) RBOB 5) WTI: '))
    
            if inst==1:
                product='B'
                break
            elif inst==2:
                product='G'
                break   
            elif inst==3:
                product='HO'
                break      
            elif inst==4:
                product='RB'
                break       
            elif inst==5:
                product='CL'
                break       
            else:
                print 'You did not input a correct number. Please try again.'
        
        return product
        
    
    def mth_no2(self):
        month=''
        while True:
            Mth=int(raw_input('Please input the month of the contract which you wish to evaluate in numbers from 1-12: '))
    
            if Mth==1:
                month='Jan'
                break
            elif Mth==2:
                month='Feb'
                break   
            elif Mth==3:
                month='Mar'
                break   
            elif Mth==4:
                month='Apr'
                break   
            elif Mth==5:
                month='May'
                break          
            elif Mth==6:
                month='Jun'
                break   
            elif Mth==7:
                month='Jul'
                break   
            elif Mth==8:
                month='Aug'
                break   
            elif Mth==9:
                month='Sep'
                break   
            elif Mth==10:
                month='Oct'
                break   
            elif Mth==11:
                month='Nov'
                break   
            elif Mth==12:
                month='Dec'
                break 
            else:
                print 'You did not input a correct number. Please try again.'
        
        return month

In [349]:
import numpy as np
import pandas as pd
import os
import statsmodels.tsa.stattools as ts
import statsmodels.api as sm
import matplotlib.pyplot as plt  
%matplotlib inline

In [350]:
### user specify instrument and contract month

product1=''
month1=''
product2=''
month2=''

front_mth=Mth_1()
product1 = front_mth.pdt_type1()
month1=front_mth.mth_no1()
#seasonal_year1=str(raw_input('Please specify the contract year: '))

back_mth=Mth_2()
product2=back_mth.pdt_type2()
month2=back_mth.mth_no2()
#seasonal_year2=str(raw_input('Please specify the contract year: '))

#user specify period
start_mth=raw_input('Please input start mth of seasonal period in MM format: ')
start_day=raw_input('Please input start day of seasonal period in DD format: ')
i=int(raw_input('Please input integers -1,0,or +1 to add on to current year for start date year: '))
            
end_mth=raw_input('Please input end mth of seasonal period in MM format: ')
end_day=raw_input('Please input end day of seasonal period in DD format: ')
            
j=int(raw_input('Please input integers -1,0, or +1 to add on to current year for end date year: '))

Please input the number of the product you want to see the seasonals: 1) Brent 2) Gasoil 3) HO 4) RBOB 5) WTI: 4
Please input the month of the contract which you wish to evaluate in numbers from 1-12: 12
Please input the number of the product you want to see the seasonals: 1) Brent 2) Gasoil 3) HO 4) RBOB 5) WTI: 5
Please input the month of the contract which you wish to evaluate in numbers from 1-12: 12
Please input start mth of seasonal period in MM format: 05
Please input start day of seasonal period in DD format: 01
Please input integers -1,0,or +1 to add on to current year for start date year: 0
Please input end mth of seasonal period in MM format: 10
Please input end day of seasonal period in DD format: 25
Please input integers -1,0, or +1 to add on to current year for end date year: 0

In [351]:
start_year=int(raw_input('Please input the start year of contract year: '))
end_year=int(raw_input('Please input the end year of contract year: '))

#input lookback period
lookback=int(raw_input('Please input the lookback period: '))

#creating entry and exit signals
z_score_entry=float(raw_input('Please input the z score for trade entry as a positive float number: '))
z_score_exit=float(raw_input('Please input the z score for trade exit as a positive float number: '))

adf_store=pd.DataFrame(index=np.arange(start_year,end_year+1),columns=np.arange(0,1))
adf_store=adf_store.rename(columns={0:'adf'})

final_pnl_store=pd.DataFrame(index=np.arange(start_year,end_year+1),columns=np.arange(0,1))
final_pnl_store=final_pnl_store.rename(columns={0:'final_pnl'})

hedge_ratio_store=pd.DataFrame(index=np.arange(start_year,end_year+1),columns=np.arange(0,1))
hedge_ratio_store=hedge_ratio_store.rename(columns={0:'hedge_ratio'})
                               
final_pnl_hr_store=pd.DataFrame(index=np.arange(start_year,end_year+1),columns=np.arange(0,1))
final_pnl_hr_store=final_pnl_hr_store.rename(columns={0:'final_pnl_hr'})

min_pnl_store=pd.DataFrame(index=np.arange(start_year,end_year+1),columns=np.arange(0,1))
min_pnl_store=min_pnl_store.rename(columns={0:'min_pnl'})


a=0

while a<end_year-start_year:
    %cd Quandl
    %cd $product1        
    %cd $month1  
    
    
    #read files - #front month

    path = os.getcwd()
    listing = os.listdir(path)

    month=month1+" "+str(start_year+a)+".xls"
    
    temp = pd.DataFrame()
    temp1=pd.DataFrame()
        
    for infile in listing:
        if infile==month:
            temp=pd.read_excel(infile)
        else:
            pass

    start_date=str(start_year+a+i)+'-'+start_mth+'-'+start_day # create start date 
    end_date=str(start_year+a+j)+'-'+end_mth+'-'+end_day # create end date 

    #Join a date series and temp together

    dates=pd.date_range(start_date, end_date) # range of dates for date axis
    dates=dates.strftime('%Y-%m-%d') #make sure no left out dates
    sample_data=np.arange(0,len(dates)) #just sample numbers to create dataframe

    dates_dataframe=pd.DataFrame({'Date':dates,'data':sample_data}) # create dates dataframe
    dates_dataframe=dates_dataframe.set_index('Date') # set index as Date to facilitate joining

    temp=temp.set_index('Date') # set index as Date to facilitate joining via dates
    temp=dates_dataframe.join(temp) # join dataframes together on Date

    #filter dates by the start and end date
    temp.reset_index(inplace=True)
    
    temp=temp[temp['Date']>=start_date] # filter for start date

    temp=temp[temp['Date']<=end_date] # filter for end date

    temp['Date']=pd.to_datetime(temp['Date']).dt.strftime('%m/%d') # putting date in mm/dd form
    temp=temp.set_index('Date') # putting date back as index

    temp=pd.DataFrame(temp['Settle'],columns=['Settle']) # setting dataframe with date and settle only
    temp=temp.rename(index=str,columns={"Settle":"Front_Month_Settle"})
    
    %cd ..
    %cd ..
    %cd ..
    
    %cd Quandl
    %cd $product2
    %cd $month2
    
    
    #read files - #back month

    path = os.getcwd()
    listing = os.listdir(path)

    month=month1+" "+str(start_year+a)+".xls"

    for infile in listing:
        if infile==month:
            temp1=pd.read_excel(infile)
        else:
            pass

    start_date=str(start_year+a+i)+'-'+start_mth+'-'+start_day # create start date # assume same year
    end_date=str(start_year+a+j)+'-'+end_mth+'-'+end_day # create end date # assume same year


    #Join a date dataframe and the temp dataframe together
            
    dates=pd.date_range(start_date, end_date) # range of dates for date axis
    dates=dates.strftime('%Y-%m-%d') #make sure no left out dates
    sample_data=np.arange(0,len(dates)) #just sample numbers to create dataframe
    
    dates_dataframe=pd.DataFrame({'Date':dates,'data':sample_data}) # create dates dataframe
    dates_dataframe=dates_dataframe.set_index('Date') # set index as Date to facilitate joining
    
    temp1=temp1.set_index('Date') # set index as Date to facilitate joining

    temp1=dates_dataframe.join(temp1) # join dataframes together on Date

    #filter dates by the start and end date
    temp1.reset_index(inplace=True)
    
    temp1=temp1[temp1['Date']>=start_date] # filter for start date

    temp1=temp1[temp1['Date']<=end_date] # filter for end date

    temp1['Date']=pd.to_datetime(temp1['Date']).dt.strftime('%m/%d') # putting date in mm/dd form
    temp1=temp1.set_index('Date') # putting date back as index
    temp1=pd.DataFrame(temp1['Settle'],columns=['Settle'])
    temp1=temp1.rename(index=str,columns={"Settle":"Back_Month_Settle"})

    #join front month and back month

    temp=temp.join(temp1)
    
    %cd ..
    %cd ..
    %cd ..
  
    #drop rows with all NAs
    temp.dropna(axis=0,how='any',inplace=True) # drop rows with all NAs
    
    zf=apply_factor(product1,product2)
    
    #adf calculation
    temp['Spread']=temp['Front_Month_Settle']*zf[0]-temp['Back_Month_Settle']*zf[1]
    adf=float(ts.adfuller(temp['Spread'])[0])  
    
    ##adf store
    adf_store.loc[start_year+a]=adf
    
    #creating MA and STD and z_score
    temp['MA']=pd.rolling_mean(temp['Spread'],lookback)
    temp['M_STD']=pd.rolling_std(temp['Spread'],lookback)  
    temp['z_score']=(temp['Spread']-temp['MA'])/temp['M_STD']

    #creating positions
    temp['long_entry']=temp['z_score'] <= -z_score_entry
    temp['long_exit']=temp['z_score']>=-z_score_exit
    temp['short_entry']=temp['z_score']>=z_score_entry
    temp['short_exit']=temp['z_score']<=z_score_exit
    
    temp['long_entry'][temp['long_entry']==True]=2
    temp['long_exit'][temp['long_exit']==True]=-1

    temp['short_entry'][temp['short_entry']==True]=-2
    temp['short_exit'][temp['short_exit']==True]=1

    temp['long_positions']=temp['long_entry']+temp['long_exit']

    temp['long_positions'][temp['long_positions']==0]=np.nan
    temp['long_positions'][temp['long_positions']==-1]=0
    temp['long_positions'][temp['long_positions']==2]=1
    temp['long_positions']=temp['long_positions'].fillna(method='ffill')

    temp['short_positions']=temp['short_entry']+temp['short_exit']
    temp['short_positions'][temp['short_positions']==0]=np.nan
    temp['short_positions'][temp['short_positions']==1]=0
    temp['short_positions'][temp['short_positions']==-2]=-1
    temp['short_positions']=temp['short_positions'].fillna(method='ffill')
                            
    temp['positions']=temp['long_positions']+temp['short_positions']  
    
    
    #hedge ratio calculation
    model=sm.OLS(temp['Front_Month_Settle']*zf[0], temp['Back_Month_Settle']*zf[1])
    model=model.fit()
    hedge_ratio=model.params[0]
    
    
    #hedge ratio store
    hedge_ratio_store.loc[start_year+a]=hedge_ratio
    
    #pnl calculation
    temp['pnl']=temp['positions'].shift(1)*(temp['Spread']-temp['Spread'].shift(1))*1000
    temp['cumpnl']=temp['pnl'].cumsum()
    final_pnl=temp['cumpnl'].tail(1)[0]
    
    #final pnl store
    
    final_pnl_store.loc[start_year+a]=final_pnl
     
    #min pnl calculation
    min_pnl=temp['cumpnl'].min()
        
    #min_pnl store
    min_pnl_store.loc[start_year+a]=min_pnl
        
    #using hedge ratio
    temp['Spread_hr']=temp['Front_Month_Settle']*zf[0]-hedge_ratio*temp['Back_Month_Settle']*zf[1]

    adf_hr=float(ts.adfuller(temp['Spread_hr'])[0])
    temp['pnl_hr']=temp['positions'].shift(1)*(temp['Spread_hr']-temp['Spread_hr'].shift(1))*1000
    temp['cumpnl_hr']=temp['pnl_hr'].cumsum()
    final_pnl_hr=temp['cumpnl_hr'].tail(1)[0]
    
    final_pnl_hr_store.loc[start_year+a]=final_pnl_hr
    
    a+=1

Please input the start year of contract year: 1996
Please input the end year of contract year: 2018
Please input the lookback period: 20
Please input the z score for trade entry as a positive float number: 2.5
Please input the z score for trade exit as a positive float number: 0
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:151: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=20,center=False).mean()
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:152: FutureWarning: pd.rolling_std is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=20,center=False).std()
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:164: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:177: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec

C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl\RB\Dec
C:\Users\boonsin.teo\Documents\Quandl\RB
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl\CL\Dec
C:\Users\boonsin.teo\Documents\Quandl\CL
C:\Users\boonsin.teo\Documents\Quandl
C:\Users\boonsin.teo\Documents

In [352]:
adf_store

           adf
1996  -1.33781
1997  -1.40279
1998  -2.02803
1999  -2.50666
2000  -2.19936
2001  -1.65387
2002  -2.20781
2003  -4.99746
2004  -1.16202
2005  -1.15268
2006   -1.7582
2007 -0.348772
2008 -0.845046
2009  -2.39409
2010  -2.10204
2011  -1.64197
2012 -0.838491
2013  -1.14454
2014  -1.04384
2015  -1.89911
2016 -0.678391
2017  -4.23235
2018       NaN

In [353]:
hedge_ratio_store

     hedge_ratio
1996     1.16834
1997      1.1797
1998     1.25626
1999     1.18709
2000     1.15566
2001      1.1503
2002     1.13894
2003     1.14077
2004     1.14925
2005     1.13312
2006     1.09351
2007      1.1066
2008     1.01161
2009     1.05216
2010     1.04915
2011     1.22181
2012     1.19179
2013     1.12353
2014      1.1302
2015     1.21379
2016      1.1836
2017     1.24345
2018         NaN

In [354]:
final_pnl_store

     final_pnl
1996     -62.6
1997       313
1998    -114.2
1999     439.4
2000     786.4
2001      1072
2002       704
2003     920.4
2004      1351
2005      2709
2006         0
2007    -453.8
2008     -1589
2009    -751.8
2010    1159.8
2011    6083.6
2012    1416.2
2013       419
2014      2803
2015    1356.6
2016      1629
2017   -2339.2
2018       NaN

In [355]:
final_pnl_hr_store

     final_pnl_hr
1996     -212.427
1997      320.188
1998      288.127
1999      516.108
2000      1208.25
2001      1037.43
2002      148.238
2003      865.502
2004      1455.48
2005      1730.57
2006            0
2007      -171.32
2008     -1246.97
2009      3.99822
2010      923.895
2011      3466.23
2012      4780.24
2013     -71.4055
2014       4144.1
2015     -80.0769
2016      3011.54
2017      -1859.6
2018          NaN

In [356]:
min_pnl_store

     min_pnl
1996  -532.8
1997  -140.2
1998    -585
1999  -295.8
2000  -265.2
2001       0
2002  -229.6
2003       0
2004   762.4
2005   -4733
2006       0
2007 -1744.6
2008   -1589
2009 -2073.6
2010  -601.8
2011   -2729
2012   -2647
2013 -2176.6
2014  -420.8
2015    -593
2016   -65.2
2017 -3748.6
2018     NaN

In [357]:
#print results

print 'The sum of final pnl across years w/o using hedge ratio is %.2f.' %final_pnl_store.sum()
win_percent=(final_pnl_store[final_pnl_store>=0].count()/final_pnl_store.count())*100
print 'The winning percentage of trades across years w/o using hedge ratio is %.2f percent.' %win_percent

print 'The sum of final pnl across years using hedge ratio is %.2f.' %final_pnl_hr_store.sum()
win_percent_hr=(final_pnl_hr_store[final_pnl_hr_store>=0].count()/final_pnl_hr_store.count())*100
print 'The winning percentage of trades across years using hedge ratio is %.2f percent.' %win_percent_hr

The sum of final pnl across years w/o using hedge ratio is 17851.80.
The winning percentage of trades across years w/o using hedge ratio is 72.73 percent.
The sum of final pnl across years using hedge ratio is 20258.10.
The winning percentage of trades across years using hedge ratio is 72.73 percent.

In [358]:
min_pnl_store

     min_pnl
1996  -532.8
1997  -140.2
1998    -585
1999  -295.8
2000  -265.2
2001       0
2002  -229.6
2003       0
2004   762.4
2005   -4733
2006       0
2007 -1744.6
2008   -1589
2009 -2073.6
2010  -601.8
2011   -2729
2012   -2647
2013 -2176.6
2014  -420.8
2015    -593
2016   -65.2
2017 -3748.6
2018     NaN

In [359]:
temp

,Front_Month_Settle,Back_Month_Settle,Spread,MA,M_STD,z_score,long_entry,long_exit,short_entry,short_exit,long_positions,short_positions,positions,pnl,cumpnl,Spread_hr,pnl_hr,cumpnl_hr
Date,,,,,,,,,,,,,,,,,,
05/01,1.3852,50.18,7.9984,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-4.217947,NaN,NaN
05/02,1.3635,49.10,8.1670,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.786421,NaN,NaN
05/03,1.3748,49.32,8.4216,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.585380,NaN,NaN
05/04,1.3211,47.23,8.2562,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.241968,NaN,NaN
05/05,1.3446,47.98,8.4932,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.187556,NaN,NaN
05/08,1.3568,48.31,8.6756,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.085495,NaN,NaN
05/09,1.3357,47.73,8.3694,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.250494,NaN,NaN
05/10,1.3727,48.98,8.6734,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.250807,NaN,NaN
05/11,1.3873,49.43,8.8366,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.197160,NaN,NaN
05/12,1.3906,49.26,9.1452,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.847173,NaN,NaN
05/15,1.4108,50.07,9.1836,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-3.005968,NaN,NaN
05/16,1.4189,50.11,9.4838,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.715506,NaN,NaN
05/17,1.4276,50.53,9.4292,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.872355,NaN,NaN
05/18,1.4355,50.63,9.6610,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.664900,NaN,NaN
05/19,1.4696,51.56,10.1632,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.389109,NaN,NaN
05/22,1.4812,52.05,10.1604,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.511200,NaN,NaN
05/23,1.4848,52.30,10.0616,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-2.670863,NaN,NaN
05/24,0.0606,52.09,-49.5448,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-62.226138,NaN,NaN
05/25,1.4313,49.76,10.3546,NaN,NaN,NaN,False,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-1.759498,NaN,NaN
05/26,1.4487,50.59,10.2554,6.21223,13.146314,0.307552,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-2.060762,NaN,NaN
05/30,1.4465,50.48,10.2730,6.32596,13.172393,0.299645,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-2.016383,NaN,NaN
05/31,1.4159,49.12,10.3478,6.43500,13.197437,0.296482,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-1.610490,NaN,NaN
06/01,1.4149,49.22,10.2058,6.52421,13.217588,0.278537,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-1.776835,NaN,NaN
06/02,1.3949,48.51,10.0758,6.61519,13.236386,0.261447,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-1.733985,NaN,NaN
06/05,1.3742,48.22,9.4964,6.66535,13.245775,0.213732,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-2.242784,NaN,NaN
06/06,1.3853,48.88,9.3026,6.69670,13.251524,0.196649,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-2.597262,NaN,NaN
06/07,1.3380,46.87,9.3260,6.74453,13.259603,0.194687,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-2.084526,NaN,NaN
06/08,1.3396,46.85,9.4132,6.78152,13.266297,0.198373,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-1.992457,NaN,NaN
06/09,1.3488,46.97,9.6796,6.82367,13.274507,0.215144,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-1.755271,NaN,NaN
06/12,1.3444,47.15,9.3148,6.83215,13.276122,0.187001,False,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,-2.163892,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
09/14,1.5714,50.66,15.3388,14.55506,1.204977,0.650419,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,291.2,-2756.8,3.005596,427.532295,-2708.109895
09/15,1.5896,50.81,15.9532,14.70417,1.182955,1.055856,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,-614.4,-3371.2,3.583479,-577.882421,-3285.992316
09/18,1.5810,50.66,15.7420,14.83733,1.139458,0.793948,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,211.2,-3160.0,3.408796,174.682421,-3111.309895
09/19,1.5718,50.24,15.7756,14.98447,1.053768,0.750763,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,-33.6,-3193.6,3.544646,-135.849221,-3247.159116
09/20,1.5884,51.04,15.6728,15.13379,0.913203,0.590241,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,102.8,-3090.8,3.247085,297.560421,-2949.598695
09/21,1.5834,50.93,15.5728,15.25913,0.776213,0.404103,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,100.0,-2990.8,3.173865,73.220442,-2876.378253
09/22,1.5990,51.03,16.1280,15.37243,0.725254,1.041801,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,-555.2,-3546.0,3.704720,-530.854947,-3407.233200
09/25,1.6393,52.52,16.3306,15.51749,0.594525,1.367663,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,-202.6,-3748.6,3.544578,160.141284,-3247.091916
09/26,1.6243,52.19,16.0306,15.60203,0.535534,0.800267,False,-1.0,0.0,0.0,0.0,-1.0,-1.0,300.0,-3448.6,3.324917,219.661326,-3027.430590
09/27,1.6036,52.43,14.9212,15.61868,0.506758,-1.376358,False,0.0,0.0,1.0,0.0,0.0,0.0,1109.4,-2339.2,2.157089,1167.828126,-1859.602463
09/28,1.5970,51.87,15.2040,15.64791,0.460867,-0.963206,False,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-2339.2,2.576221,0.000000,-1859.602463
09/29,1.5787,51.95,14.3554,15.56682,0.536372,-2.258543,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,1.708145,-0.000000,-1859.602463
10/02,1.5515,50.90,14.2630,15.48179,0.601057,-2.027744,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,1.871368,0.000000,-1859.602463
10/03,1.5583,50.74,14.7086,15.47232,0.612129,-1.247645,False,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-2339.2,2.355920,0.000000,-1859.602463
10/04,1.5685,50.32,15.5570,15.50609,0.596249,0.085384,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,3.306570,0.000000,-1859.602463
10/05,1.5966,51.15,15.9072,15.55077,0.590859,0.603241,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,3.454706,0.000000,-1859.602463
10/06,1.5474,49.65,15.3408,15.51853,0.583429,-0.304630,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,3.253481,-0.000000,-1859.602463
10/09,1.5463,49.93,15.0146,15.48519,0.592611,-0.794095,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,2.859115,-0.000000,-1859.602463
10/10,1.5753,51.23,14.9326,15.41894,0.575533,-0.845025,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,2.460630,-0.000000,-1859.602463
10/11,1.5885,51.60,15.1170,15.39329,0.577061,-0.478788,False,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-2339.2,2.554953,0.000000,-1859.602463
10/12,1.5645,50.93,14.7790,15.36530,0.593194,-0.988377,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,2.380065,-0.000000,-1859.602463
10/13,1.6008,51.73,15.5036,15.34282,0.578069,0.278133,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,2.909904,0.000000,-1859.602463
10/16,1.5994,52.14,15.0348,15.30746,0.573981,-0.475033,False,0.0,0.0,1.0,0.0,0.0,0.0,-0.0,-2339.2,2.341290,-0.000000,-1859.602463
10/17,1.6123,52.11,15.6066,15.29901,0.567939,0.541590,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,2.920393,0.000000,-1859.602463
10/18,1.6190,52.26,15.7380,15.30227,0.570379,0.763931,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,3.015276,0.000000,-1859.602463
10/19,1.6154,51.51,16.3368,15.34047,0.613411,1.624245,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,3.796663,0.000000,-1859.602463
10/20,1.6435,51.84,17.1870,15.39342,0.721205,2.486922,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,4.566525,0.000000,-1859.602463
10/23,1.6390,51.90,16.9380,15.42379,0.773630,1.957279,False,-1.0,0.0,0.0,0.0,0.0,0.0,-0.0,-2339.2,4.302918,-0.000000,-1859.602463
10/24,1.6734,52.47,17.8128,15.51290,0.933356,2.464120,False,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-2339.2,5.038951,0.000000,-1859.602463
10/25,1.6861,52.18,18.6362,15.69865,1.153182,2.547343,False,-1.0,-2.0,0.0,0.0,-1.0,-1.0,0.0,-2339.2,5.932952,0.000000,-1859.602463